### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jrcanicula** [TradeWaves/ct-interview-46cdb146#1]
@agsydney 

"One of those is the ASX listed companies. The list of companies is available online as a CSV (the URL is in the appsettings). An example CSV file is included in the Docs folder. **Also that list is updated once a day.** "

Should this one have a scheduler of just an API that get the form the URL?

**Comment by agsydney** [comment]
You have to make that decision :)

What would you do to make it highly efficient, resilient and production ready and showing what you can do?

**Comment by jrcanicula** [comment]
Got you. 

Supposed i have a scheduler for example.  How can I show that to you, given that I just need to submit a code, if I won't host it i.e Windows Task Scheduler, Azure Functions, AWS Lambda?

**Comment by agsydney** [comment]
There's a way to do that in a .netcore webapi project. Remember what i mentioned about hostedservices

**Comment by jrcanicula** [comment]
I see I see. Will do that :)
